// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpJXxxvFUb1sTU3F6JVo_SwutpkUsH-k',
    appId: '1:289703129200:web:35f26f65b9154f4dd7c4b5',
    messagingSenderId: '289703129200',
    projectId: 'milestone-firestore-demo',
    authDomain: 'milestone-firestore-demo.firebaseapp.com',
    storageBucket: 'milestone-firestore-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tK3UHB-JJR0uzFo7VOuVgRlq8e8E2RU',
    appId: '1:289703129200:ios:d1ab3cb567bc39a0d7c4b5',
    messagingSenderId: '289703129200',
    projectId: 'milestone-firestore-demo',
    storageBucket: 'milestone-firestore-demo.appspot.com',
    iosBundleId: 'com.example.firestoreWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tK3UHB-JJR0uzFo7VOuVgRlq8e8E2RU',
    appId: '1:289703129200:ios:8588d425c19988b8d7c4b5',
    messagingSenderId: '289703129200',
    projectId: 'milestone-firestore-demo',
    storageBucket: 'milestone-firestore-demo.appspot.com',
    iosBundleId: 'com.example.firestoreWebapp.RunnerTests',
  );
}
